services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=XXXXX
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - '3336:3306'
  web:
    image: tomcat:10.1.13
    ports:
      - "80:8080"
    volumes:
      - webapps:/usr/local/tomcat/webapps
    links:
      - mariadb
volumes:
  webapps:
